# .pre-commit-config.yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0 # pick a tag
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint