repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: local
    hooks:
      - id: sam-validate
        name: Run `sam validate` on template.yml
        entry: sam validate --template-file lambda/template.yml
        language: system
        pass_filenames: false