name: SAM Validate

on:
  push:
    paths:
      - '**/template*.yml'
  pull_request:
    paths:
      - '**/template*.yml'

jobs:
  sam-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Validate SAM template
        run: sam validate --template-file lambda/template.yml