# .github/workflows/terraform-lint.yml
name: Terraform Lint

on:
  push:
    paths:
      - "terraform/**.tf"
      - ".github/workflows/terraform-lint.yml"
  pull_request:
    paths:
      - "terraform/**.tf"
      - ".github/workflows/terraform-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Install TFLint (correct action)
      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      # Init without backend to avoid needing cloud creds just for validate
      - name: Terraform init (no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: TFLint init (download plugins)
        run: tflint --init

      - name: TFLint
        run: tflint -f compact